// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLsPbYJOcjs1LpeT2TE40-cTqNUOQQCiI',
    appId: '1:241977329014:web:4847e457a63f21835ee657',
    messagingSenderId: '241977329014',
    projectId: 'example-011-13194',
    authDomain: 'example-011-13194.firebaseapp.com',
    storageBucket: 'example-011-13194.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJO16tQcyl-YZi1Y4pDZq96swng5-Nmz0',
    appId: '1:241977329014:android:2cf21e35d19abedc5ee657',
    messagingSenderId: '241977329014',
    projectId: 'example-011-13194',
    storageBucket: 'example-011-13194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPhrjZDQFW476wwf4MVGJYMRbBA2CDYmM',
    appId: '1:241977329014:ios:f6df4475063729835ee657',
    messagingSenderId: '241977329014',
    projectId: 'example-011-13194',
    storageBucket: 'example-011-13194.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPhrjZDQFW476wwf4MVGJYMRbBA2CDYmM',
    appId: '1:241977329014:ios:9cac95ad987482a25ee657',
    messagingSenderId: '241977329014',
    projectId: 'example-011-13194',
    storageBucket: 'example-011-13194.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
